In [14]:
import torch as t
import numpy as np
x = t.Tensor(5,3)

In [3]:
x

tensor([[1.0102e-38, 1.0102e-38, 8.4490e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [1.0194e-38, 9.0919e-39, 8.4490e-39]])

In [4]:
x = t.rand(5,3)
x

tensor([[0.9153, 0.1058, 0.7561],
        [0.2916, 0.6148, 0.0631],
        [0.7947, 0.4844, 0.6126],
        [0.0635, 0.8541, 0.1412],
        [0.1650, 0.1104, 0.9947]])

In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = t.rand(5,3)
t.add(x,y)

tensor([[1.7763, 0.7971, 0.9364],
        [1.2745, 1.1765, 0.8845],
        [1.0351, 0.8100, 1.2991],
        [0.1831, 1.5257, 1.0680],
        [0.3724, 0.3679, 1.1082]])

In [10]:
result = t.Tensor(5,3)
t.add(x,y,out=result)
result

tensor([[1.7763, 0.7971, 0.9364],
        [1.2745, 1.1765, 0.8845],
        [1.0351, 0.8100, 1.2991],
        [0.1831, 1.5257, 1.0680],
        [0.3724, 0.3679, 1.1082]])

In [11]:
print("最初y")
print(y)

print("第一种加法，y的结果")
y.add(x)
print(y)

print("第二种加法,y的结果")
y.add_(x)
print(y)

最初y
tensor([[0.8610, 0.6913, 0.1802],
        [0.9829, 0.5616, 0.8214],
        [0.2403, 0.3256, 0.6865],
        [0.1196, 0.6716, 0.9268],
        [0.2074, 0.2575, 0.1134]])
第一种加法，y的结果
tensor([[0.8610, 0.6913, 0.1802],
        [0.9829, 0.5616, 0.8214],
        [0.2403, 0.3256, 0.6865],
        [0.1196, 0.6716, 0.9268],
        [0.2074, 0.2575, 0.1134]])
第二种加法,y的结果
tensor([[1.7763, 0.7971, 0.9364],
        [1.2745, 1.1765, 0.8845],
        [1.0351, 0.8100, 1.2991],
        [0.1831, 1.5257, 1.0680],
        [0.3724, 0.3679, 1.1082]])


In [12]:
b = x.numpy()

In [13]:
b

array([[0.91527206, 0.1057539 , 0.75613457],
       [0.29157132, 0.61483246, 0.06307381],
       [0.79473174, 0.484401  , 0.6125984 ],
       [0.06351846, 0.85410166, 0.14124417],
       [0.16499662, 0.11043751, 0.99474883]], dtype=float32)

In [17]:
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x+y

In [20]:
print(t.cuda.is_available())

False


In [21]:
from torch.autograd import Variable
x = Variable(t.ones(2,2),requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [23]:
y.grad_fn

In [25]:
y.backward()

In [29]:
y = x.sum() = (x[0][0] + x[0][1] + x[1][0] + x[1][1])
x.grad

SyntaxError: can't assign to function call (<ipython-input-29-6363650e44a8>, line 1)